// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  organization_id, name, email, phone, document, type
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, organization_id, name, email, phone, document, type, created_at, updated_at
`

type CreateCustomerParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	Document       pgtype.Text `json:"document"`
	Type           pgtype.Text `json:"type"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.OrganizationID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Document,
		arg.Type,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Document,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1 AND organization_id = $2
`

type DeleteCustomerParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.OrganizationID)
	return err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, organization_id, name, email, phone, document, type, created_at, updated_at FROM customers
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCustomers(ctx context.Context, organizationID pgtype.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Document,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $3, email = $4, phone = $5, document = $6, type = $7, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, email, phone, document, type, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	Document       pgtype.Text `json:"document"`
	Type           pgtype.Text `json:"type"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Document,
		arg.Type,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Document,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
