// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardMetrics = `-- name: GetDashboardMetrics :one
SELECT
    COALESCE((SELECT SUM(total_amount) FROM orders o WHERE o.organization_id = $1::uuid AND o.status = 'completed'), 0)::FLOAT AS total_revenue,
    (SELECT COUNT(*) FROM orders o2 WHERE o2.organization_id = $1::uuid AND o2.status = 'completed')::INT AS sales_count,
    (SELECT COUNT(*) FROM customers c WHERE c.organization_id = $1::uuid)::INT AS customers_count,
    (SELECT COUNT(*) FROM products p WHERE p.organization_id = $1::uuid AND p.stock_quantity < 5)::INT AS low_stock_count
`

type GetDashboardMetricsRow struct {
	TotalRevenue   float64 `json:"total_revenue"`
	SalesCount     int32   `json:"sales_count"`
	CustomersCount int32   `json:"customers_count"`
	LowStockCount  int32   `json:"low_stock_count"`
}

func (q *Queries) GetDashboardMetrics(ctx context.Context, dollar_1 pgtype.UUID) (GetDashboardMetricsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardMetrics, dollar_1)
	var i GetDashboardMetricsRow
	err := row.Scan(
		&i.TotalRevenue,
		&i.SalesCount,
		&i.CustomersCount,
		&i.LowStockCount,
	)
	return i, err
}
