// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: financial.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFinancialTransaction = `-- name: CreateFinancialTransaction :one
INSERT INTO financial_transactions (
    organization_id, type, status, amount, description, due_date, paid_at, reference_type, reference_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, organization_id, type, status, amount, description, due_date, paid_at, reference_type, reference_id, created_at, updated_at
`

type CreateFinancialTransactionParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	Amount         pgtype.Numeric     `json:"amount"`
	Description    string             `json:"description"`
	DueDate        pgtype.Date        `json:"due_date"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	ReferenceType  pgtype.Text        `json:"reference_type"`
	ReferenceID    pgtype.UUID        `json:"reference_id"`
}

func (q *Queries) CreateFinancialTransaction(ctx context.Context, arg CreateFinancialTransactionParams) (FinancialTransaction, error) {
	row := q.db.QueryRow(ctx, createFinancialTransaction,
		arg.OrganizationID,
		arg.Type,
		arg.Status,
		arg.Amount,
		arg.Description,
		arg.DueDate,
		arg.PaidAt,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i FinancialTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Description,
		&i.DueDate,
		&i.PaidAt,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinancialSummary = `-- name: GetFinancialSummary :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'payable' AND status = 'pending' THEN amount ELSE 0 END), 0)::decimal AS total_payable_pending,
    COALESCE(SUM(CASE WHEN type = 'receivable' AND status = 'pending' THEN amount ELSE 0 END), 0)::decimal AS total_receivable_pending
FROM financial_transactions
WHERE organization_id = $1
`

type GetFinancialSummaryRow struct {
	TotalPayablePending    pgtype.Numeric `json:"total_payable_pending"`
	TotalReceivablePending pgtype.Numeric `json:"total_receivable_pending"`
}

func (q *Queries) GetFinancialSummary(ctx context.Context, organizationID pgtype.UUID) (GetFinancialSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFinancialSummary, organizationID)
	var i GetFinancialSummaryRow
	err := row.Scan(&i.TotalPayablePending, &i.TotalReceivablePending)
	return i, err
}

const getFinancialTransaction = `-- name: GetFinancialTransaction :one
SELECT id, organization_id, type, status, amount, description, due_date, paid_at, reference_type, reference_id, created_at, updated_at FROM financial_transactions
WHERE id = $1 AND organization_id = $2
`

type GetFinancialTransactionParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetFinancialTransaction(ctx context.Context, arg GetFinancialTransactionParams) (FinancialTransaction, error) {
	row := q.db.QueryRow(ctx, getFinancialTransaction, arg.ID, arg.OrganizationID)
	var i FinancialTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Description,
		&i.DueDate,
		&i.PaidAt,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFinancialTransactions = `-- name: ListFinancialTransactions :many
SELECT id, organization_id, type, status, amount, description, due_date, paid_at, reference_type, reference_id, created_at, updated_at FROM financial_transactions
WHERE organization_id = $1
AND ($2::varchar IS NULL OR type = $2)
AND ($3::varchar IS NULL OR status = $3)
ORDER BY due_date ASC, created_at DESC
`

type ListFinancialTransactionsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Type           pgtype.Text `json:"type"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) ListFinancialTransactions(ctx context.Context, arg ListFinancialTransactionsParams) ([]FinancialTransaction, error) {
	rows, err := q.db.Query(ctx, listFinancialTransactions, arg.OrganizationID, arg.Type, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinancialTransaction
	for rows.Next() {
		var i FinancialTransaction
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Type,
			&i.Status,
			&i.Amount,
			&i.Description,
			&i.DueDate,
			&i.PaidAt,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFinancialTransactionStatus = `-- name: UpdateFinancialTransactionStatus :one
UPDATE financial_transactions
SET
    status = $3,
    paid_at = $4,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, type, status, amount, description, due_date, paid_at, reference_type, reference_id, created_at, updated_at
`

type UpdateFinancialTransactionStatusParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Status         string             `json:"status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateFinancialTransactionStatus(ctx context.Context, arg UpdateFinancialTransactionStatusParams) (FinancialTransaction, error) {
	row := q.db.QueryRow(ctx, updateFinancialTransactionStatus,
		arg.ID,
		arg.OrganizationID,
		arg.Status,
		arg.PaidAt,
	)
	var i FinancialTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.Description,
		&i.DueDate,
		&i.PaidAt,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
