// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: financial.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFinancialTransaction = `-- name: CreateFinancialTransaction :one
INSERT INTO financial_transactions (
    organization_id, type, amount, description, status, payment_method, order_id, due_date, paid_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, organization_id, type, amount, description, status, payment_method, order_id, due_date, paid_at, created_at
`

type CreateFinancialTransactionParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Type           string             `json:"type"`
	Amount         pgtype.Numeric     `json:"amount"`
	Description    string             `json:"description"`
	Status         string             `json:"status"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
	OrderID        pgtype.UUID        `json:"order_id"`
	DueDate        pgtype.Date        `json:"due_date"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreateFinancialTransaction(ctx context.Context, arg CreateFinancialTransactionParams) (FinancialTransaction, error) {
	row := q.db.QueryRow(ctx, createFinancialTransaction,
		arg.OrganizationID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.Status,
		arg.PaymentMethod,
		arg.OrderID,
		arg.DueDate,
		arg.PaidAt,
	)
	var i FinancialTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.PaymentMethod,
		&i.OrderID,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFinancialTransactions = `-- name: ListFinancialTransactions :many
SELECT id, organization_id, type, amount, description, status, payment_method, order_id, due_date, paid_at, created_at FROM financial_transactions
WHERE organization_id = $1
ORDER BY due_date DESC
`

func (q *Queries) ListFinancialTransactions(ctx context.Context, organizationID pgtype.UUID) ([]FinancialTransaction, error) {
	rows, err := q.db.Query(ctx, listFinancialTransactions, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinancialTransaction
	for rows.Next() {
		var i FinancialTransaction
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Status,
			&i.PaymentMethod,
			&i.OrderID,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFinancialTransactionStatus = `-- name: UpdateFinancialTransactionStatus :exec
UPDATE financial_transactions
SET status = $2, paid_at = $3
WHERE id = $1 AND organization_id = $4
`

type UpdateFinancialTransactionStatusParams struct {
	ID             pgtype.UUID        `json:"id"`
	Status         string             `json:"status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

func (q *Queries) UpdateFinancialTransactionStatus(ctx context.Context, arg UpdateFinancialTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateFinancialTransactionStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.OrganizationID,
	)
	return err
}
