// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  organization_id, name, description, price, stock_quantity, sku
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, organization_id, name, description, price, stock_quantity, sku, is_active, created_at, updated_at
`

type CreateProductParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Name           string         `json:"name"`
	Description    pgtype.Text    `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	StockQuantity  int32          `json:"stock_quantity"`
	Sku            pgtype.Text    `json:"sku"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
		arg.Sku,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.Sku,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductMetrics = `-- name: GetProductMetrics :one
SELECT
  COUNT(*) as total_products,
  SUM(CASE WHEN stock_quantity < 5 THEN 1 ELSE 0 END)::BIGINT as low_stock_count
FROM products
WHERE organization_id = $1
`

type GetProductMetricsRow struct {
	TotalProducts int64 `json:"total_products"`
	LowStockCount int64 `json:"low_stock_count"`
}

func (q *Queries) GetProductMetrics(ctx context.Context, organizationID pgtype.UUID) (GetProductMetricsRow, error) {
	row := q.db.QueryRow(ctx, getProductMetrics, organizationID)
	var i GetProductMetricsRow
	err := row.Scan(&i.TotalProducts, &i.LowStockCount)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, organization_id, name, description, price, stock_quantity, sku, is_active, created_at, updated_at FROM products
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context, organizationID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQuantity,
			&i.Sku,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  name = $2,
  description = $3,
  price = $4,
  stock_quantity = $5,
  sku = $6,
  is_active = $7,
  updated_at = NOW()
WHERE id = $1 AND organization_id = $8
RETURNING id, organization_id, name, description, price, stock_quantity, sku, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID             pgtype.UUID    `json:"id"`
	Name           string         `json:"name"`
	Description    pgtype.Text    `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	StockQuantity  int32          `json:"stock_quantity"`
	Sku            pgtype.Text    `json:"sku"`
	IsActive       bool           `json:"is_active"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
		arg.Sku,
		arg.IsActive,
		arg.OrganizationID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.Sku,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
