// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) (OrganizationMember, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	GetDashboardMetrics(ctx context.Context, dollar_1 pgtype.UUID) (GetDashboardMetricsRow, error)
	GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsRow, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProductMetrics(ctx context.Context, organizationID pgtype.UUID) (GetProductMetricsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserOrganizations(ctx context.Context, userID pgtype.UUID) ([]GetUserOrganizationsRow, error)
	ListCustomers(ctx context.Context, organizationID pgtype.UUID) ([]Customer, error)
	ListOrders(ctx context.Context, organizationID pgtype.UUID) ([]ListOrdersRow, error)
	ListProducts(ctx context.Context, organizationID pgtype.UUID) ([]Product, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
